In [360]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [361]:
df = pd.read_csv('cereal.csv', sep=';')

In [362]:
df.head()

name          mfr         type calories protein  fat  \
0                     String  Categorical  Categorical      Int     Int  Int   
1                  100% Bran            N            C       70       4    1   
2          100% Natural Bran            Q            C      120       3    5   
3                   All-Bran            K            C       70       4    1   
4  All-Bran with Extra Fiber            K            C       50       4    0   

  sodium  fiber  carbo sugars potass vitamins shelf weight   cups     rating  
0    Int  Float  Float    Int    Int      Int   Int  Float  Float      Float  
1    130     10      5      6    280       25     3      1   0.33  68.402973  
2     15      2      8      8    135        0     3      1      1  33.983679  
3    260      9      7      5    320       25     3      1   0.33  59.425505  
4    140     14      8      0    330       25     3      1    0.5  93.704912

In [363]:
df.drop(df.index[0], inplace = True)

In [364]:
df.shape

(77, 16)

In [365]:
df.head()

name mfr type calories protein fat sodium fiber carbo  \
1                  100% Bran   N    C       70       4   1    130    10     5   
2          100% Natural Bran   Q    C      120       3   5     15     2     8   
3                   All-Bran   K    C       70       4   1    260     9     7   
4  All-Bran with Extra Fiber   K    C       50       4   0    140    14     8   
5             Almond Delight   R    C      110       2   2    200     1    14   

  sugars potass vitamins shelf weight  cups     rating  
1      6    280       25     3      1  0.33  68.402973  
2      8    135        0     3      1     1  33.983679  
3      5    320       25     3      1  0.33  59.425505  
4      0    330       25     3      1   0.5  93.704912  
5      8     -1       25     3      1  0.75  34.384843

In [366]:
X = df[['name', 'mfr', 'type', 'calories', 'protein', 'fat', 'sodium', 'fiber', 'carbo', 'sugars', 'potass', 'vitamins', 'shelf', 'weight', 'cups']]
y = df['rating']

In [367]:
X

name mfr type calories protein fat sodium fiber  \
1                   100% Bran   N    C       70       4   1    130    10   
2           100% Natural Bran   Q    C      120       3   5     15     2   
3                    All-Bran   K    C       70       4   1    260     9   
4   All-Bran with Extra Fiber   K    C       50       4   0    140    14   
5              Almond Delight   R    C      110       2   2    200     1   
..                        ...  ..  ...      ...     ...  ..    ...   ...   
73                    Triples   G    C      110       2   1    250     0   
74                       Trix   G    C      110       1   1    140     0   
75                 Wheat Chex   R    C      100       3   1    230     3   
76                   Wheaties   G    C      100       3   1    200     3   
77        Wheaties Honey Gold   G    C      110       2   1    200     1   

   carbo sugars potass vitamins shelf weight  cups  
1      5      6    280       25     3      1  0.33  
2      8      8    135        0     3      1     1  
3      7      5    320       25     3      1  0.33  
4      8      0    330       25     3      1   0.5  
5     14      8     -1       25     3      1  0.75  
..   ...    ...    ...      ...   ...    ...   ...  
73    21      3     60       25     3      1  0.75  
74    13     12     25       25     2      1     1  
75    17      3    115       25     1      1  0.67  
76    17      3    110       25     1      1     1  
77    16      8     60       25     1      1  0.75  

[77 rows x 15 columns]

In [368]:
y

1     68.402973
2     33.983679
3     59.425505
4     93.704912
5     34.384843
        ...    
73    39.106174
74    27.753301
75    49.787445
76    51.592193
77    36.187559
Name: rating, Length: 77, dtype: object

In [369]:
X.drop(["name","mfr"],axis=1,inplace=True)
X = pd.get_dummies(X, columns=['type'])

C:\Users\chand\anaconda3\lib\site-packages\pandas\core\frame.py:4906: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(


In [370]:
X

calories protein fat sodium fiber carbo sugars potass vitamins shelf  \
1        70       4   1    130    10     5      6    280       25     3   
2       120       3   5     15     2     8      8    135        0     3   
3        70       4   1    260     9     7      5    320       25     3   
4        50       4   0    140    14     8      0    330       25     3   
5       110       2   2    200     1    14      8     -1       25     3   
..      ...     ...  ..    ...   ...   ...    ...    ...      ...   ...   
73      110       2   1    250     0    21      3     60       25     3   
74      110       1   1    140     0    13     12     25       25     2   
75      100       3   1    230     3    17      3    115       25     1   
76      100       3   1    200     3    17      3    110       25     1   
77      110       2   1    200     1    16      8     60       25     1   

   weight  cups  type_C  type_H  
1       1  0.33       1       0  
2       1     1       1       0  
3       1  0.33       1       0  
4       1   0.5       1       0  
5       1  0.75       1       0  
..    ...   ...     ...     ...  
73      1  0.75       1       0  
74      1     1       1       0  
75      1  0.67       1       0  
76      1     1       1       0  
77      1  0.75       1       0  

[77 rows x 14 columns]

In [371]:
X

calories protein fat sodium fiber carbo sugars potass vitamins shelf  \
1        70       4   1    130    10     5      6    280       25     3   
2       120       3   5     15     2     8      8    135        0     3   
3        70       4   1    260     9     7      5    320       25     3   
4        50       4   0    140    14     8      0    330       25     3   
5       110       2   2    200     1    14      8     -1       25     3   
..      ...     ...  ..    ...   ...   ...    ...    ...      ...   ...   
73      110       2   1    250     0    21      3     60       25     3   
74      110       1   1    140     0    13     12     25       25     2   
75      100       3   1    230     3    17      3    115       25     1   
76      100       3   1    200     3    17      3    110       25     1   
77      110       2   1    200     1    16      8     60       25     1   

   weight  cups  type_C  type_H  
1       1  0.33       1       0  
2       1     1       1       0  
3       1  0.33       1       0  
4       1   0.5       1       0  
5       1  0.75       1       0  
..    ...   ...     ...     ...  
73      1  0.75       1       0  
74      1     1       1       0  
75      1  0.67       1       0  
76      1     1       1       0  
77      1  0.75       1       0  

[77 rows x 14 columns]

In [372]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 15)

In [373]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [374]:
print("Intercept: ", model.intercept_)
print("Coefficients:")
list(zip(X, model.coef_))

Intercept:  54.92718423391716
Coefficients:


[('calories', -0.22272416448234447),
 ('protein', 3.2731738472755385),
 ('fat', -1.6914079868900145),
 ('sodium', -0.05449270193307696),
 ('fiber', 3.443479848171116),
 ('carbo', 1.0924509377476412),
 ('sugars', -0.7248951504292168),
 ('potass', -0.03399335274884886),
 ('vitamins', -0.051211969506708574),
 ('shelf', -3.764615198801381e-08),
 ('weight', -1.0142218329238754e-07),
 ('cups', 1.6262114508812574e-07),
 ('type_C', 1.853869691914411e-08),
 ('type_H', -1.853869741874447e-08)]

In [375]:
y_pred = model.predict(X_test)
y_pred

array([54.85091696, 35.25244363, 53.3138129 , 55.33314183, 41.99893303,
       39.70339961, 22.39651279, 31.43597287, 31.07221728, 34.13976436,
       30.31335091, 29.92428515, 93.70491275, 41.50354   , 64.53381603,
       28.59278458])

In [376]:
def estimate_coef_multiple_linear_regression(X_train,y_train):
    X_train = X_train.apply(pd.to_numeric, errors='coerce')
    y_train = y_train.apply(pd.to_numeric, errors='coerce')
    
    return np.linalg.inv(X_train.transpose().dot(X_train)).dot(X_train.transpose()).dot(y_train)

In [377]:
coef = estimate_coef_multiple_linear_regression(X_train,y_train)

In [378]:
coef

array([-2.22724164e-01,  3.27317385e+00, -1.69140799e+00, -5.44927019e-02,
        3.44347985e+00,  1.09245094e+00, -7.24895150e-01, -3.39933527e-02,
       -5.12119695e-02, -3.76461817e-08, -1.01416120e-07,  1.62621077e-07,
        5.49271843e+01,  5.49271842e+01])

In [379]:
X_test = X_test.apply(pd.to_numeric, errors='coerce')
y_test = y_test.apply(pd.to_numeric, errors='coerce')
predictions = np.dot(X_test,coef)

In [380]:
predictions

array([54.85091696, 35.25244363, 53.3138129 , 55.33314183, 41.99893303,
       39.70339961, 22.39651279, 31.43597287, 31.07221728, 34.13976436,
       30.31335091, 29.92428515, 93.70491275, 41.50354   , 64.53381603,
       28.59278458])

In [381]:
from sklearn import metrics
mae = metrics.mean_absolute_error(y_test, y_pred)
mse = metrics.mean_squared_error(y_test, y_pred)
rmse = np.sqrt(metrics.mean_squared_error(y_test, y_pred))
print('Mean Absolute Error:', mae)
print('Mean Square Error:', mse)
print('Root Mean Square Error:', rmse)

Mean Absolute Error: 2.3884196509449396e-07
Mean Square Error: 1.0335518420279782e-13
Root Mean Square Error: 3.214890110140591e-07


In [382]:
from sklearn.metrics import r2_score
r2_score(y_test, predictions)

0.9999999999999997

In [383]:
model.score(X_test, y_test)

0.9999999999999997

In [384]:
def r_squared(y_test, y_pred):
    y_bar = np.mean(y_test)
    ss_total = np.sum((y_test - y_bar) ** 2)
    sse = np.sum((y_pred - y_bar) ** 2)
    ssr = np.sum((y_test - y_pred) ** 2)
    scikit_r2 = r2_score(y_test, y_pred)
    r2score = 1 - (ssr/ss_total) 
    print('Calculated R Squared: ', r2score)
    print('Scikit R Squared: ', scikit_r2)

In [385]:
r_squared(y_test, y_pred)

Calculated R Squared:  0.9999999999999997
Scikit R Squared:  0.9999999999999997
